### ISSUE TITLE
Integrate Cloud SQL as development database

### ISSUE THREAD

**Issue by seanmstevens** [CatherineEvelyn/wedding-planner#11]
I have created a Cloud SQL instance and have my own development machine whitelisted. All I need is a list of everyone's IP addresses in order to provide access to the Cloud SQL db.

**Comment by Jgwentworth** [comment]
168.156.85.135 Jared's ip address

**Comment by KLSharkey** [comment]
Got mine set up and working!

**Comment by Jgwentworth** [comment]
jareds home ip 73.97.149.103

**Comment by KLSharkey** [comment]
It looks like my home IP address is: 98.237.255.91

**Comment by seanmstevens** [comment]
Alright, I've added Zach, Kristen, and Jared's home IP's to the whitelist. You should be able to connect from your home networks now!

**Comment by Zafuzi** [comment]
Before we can close this issue we need a way to view the tables and see all the relationships.

**Comment by seanmstevens** [comment]
In order to view the database schema, it looks like MySQL Workbench will do what we need. I'm at work right now, but once I get home I'll post detailed instructions in Slack for installation and setup. If you'd like to get started yourselves, here's the Workbench download: https://www.mysql.com/products/workbench/

And Google's documentation: https://cloud.google.com/sql/docs/mysql/admin-tools#workbench

**Comment by Zafuzi** [comment]
I am going to close this as the proposed solution is tested and works well.
