### ISSUE TITLE
Make the services page

### ISSUE THREAD

**Issue by Zafuzi** [CatherineEvelyn/wedding-planner#14]
## Problem / motivation
The services page will contain each category of services available to the user (photographers, caterers, bands, etc)

## Proposed solution
Data should be loaded dynamically using AJAX in a single page design. 
Clicking on a services section would load the data for that section into the view and replace the old view.

- [ ] Make the route to services.html
- [ ] Make the services.html page
  - [ ] Make the menu for selecting each service type
  - [ ] Create vendor_list.html template that will load from database
  - [ ] Integrate ajax to load vendor_list.html template
  - [ ] Update history state on ajax calls for forward/backward navigation
- [ ] Build database with fake data
- [ ] Connect services.html to the database and list vendors

## Possible Problems
This will require more attention to the history state since it won't be logged when the ajax call is made.

## Details
* **Related Issues:** #41 #45 (this is issue is broken down into these 2 issues)

**Comment by Zafuzi** [comment]
Had an idea on how the front end might look on this one. Let me know what you think. Also let me know if you like using Figma as a tool. https://www.figma.com/file/ajkIQS4FOpe1bMqYOJeNCaxs/wedding-planner

**Comment by seanmstevens** [comment]
I'm going to begin working on this, but I have a question. What exactly is the difference between the services.html template and the vendor_list.html template? Does the services template only include the fixed elements (side bar navigation, search filters), while the vendor list will populate with data from the database via an AJAX call?

**Comment by CatherineEvelyn** [comment]
the sitemap branch should explain Sean's question. We need to merge the sitemap branch first before start working on anything else so each page has a clear purpose. Without the sitemap branch merged, we could be working on the same page without even knowing, it will be very confusing.

**Comment by CatherineEvelyn** [comment]
I've broken down this issue into 2 parts so we can assign 1 person to do each issue. Check out issue #41 and #45

**Comment by Zafuzi** [comment]
Closed as obsolete
