### ISSUE TITLE
User login front end

### ISSUE THREAD

**Issue by KLSharkey** [CatherineEvelyn/wedding-planner#18]
## Problem / motivation
Create a template that will display the login form for users (brides/grooms)

[Post a picture here if it's a visual bug, or post a picture of the design if it's a feature]

## Proposed solution
Write out how you think you should go about solving the problem or creating the feature. If there's multiple paths, write it out
User name = "username"
and name ="password"
for name values to connect to the main.py file. 

## Details
* **Related Issues:** #16 (back end)
* **Classes/Files Affected:** main.py
* **Role:** front end

**Comment by Zafuzi** [comment]
Closed by one of the first pull requests. Refresh issue #16 to reflect current status.
