### ISSUE TITLE
Using Bulma as our CSS framework instead of Bootstrap

### ISSUE THREAD

**Issue by seanmstevens** [CatherineEvelyn/wedding-planner#26]
## Problem / motivation
Bootstrap is fine at all, but due to its popularity with web developers, sites that use Bootstrap with minimal custom CSS can tend to look the same.

## Proposed solution
Instead of Bootstrap, I propose that we use Bulma, which is a pure CSS framework that uses the same columns and grid based layout system that Bootstrap and other CSS frameworks have adopted. The great benefit of Bulma is that it doesn't have any JS dependencies, so we're able to control exactly how interactive elements work, and we don't need to override any sort of default behaviors.

Another huge benefit is that Bulma leverages SCSS, which will allow us to easily change the color variables (once we have a set color palette and aesthetic vision) in one place instead of changing those instances throughout the CSS files.

## Details
Additional information about Bulma can be found in its documentation here: http://bulma.io/documentation/overview/start/

- [x] Install Bulma via NPM or a direct download into a dependencies folder (Bulma's docs recommend the NPM solution)
- [x] Go through our HTML files and change the classes to Bulma-specific classes while preserving any custom CSS that we'd like to include
- [ ] Change SCSS color variables once we have a set color scheme

**Comment by Zafuzi** [comment]
Bulma looks nice. If everyone agrees then I am onboard. That means we would need to move to using gulp and node ASAP.

**Comment by Zafuzi** [comment]
We need to make sure not to reference the Bulma framework from the node_modules folder, since in the future I think we should combine assets using gulp and place them into a vendor file for ease of use.

**Comment by seanmstevens** [comment]
Yeah, I initially was trying to serve Bulma through node_modules and npm, but I found out that Bower works much better for front end packages, so I'm using a bower.json file in order to list the dependencies. Once we get gulp up and running, we can just combine the files and minify them in a build or assets folder.

**Comment by CatherineEvelyn** [comment]
To save time, we can leave the index.html with bootstrap for now but use bulma with the rest of the pages. When we have extra time later then we can rebuilt the index.html using bulma, but this should be very low priority for now.
