### ISSUE TITLE
create vendor table database

### ISSUE THREAD

**Issue by CatherineEvelyn** [CatherineEvelyn/wedding-planner#40]
## Problem
We need vendor table set and ready in the database so we can connect it to vendor-list.html, portfolio.html, vendor-account.html, and have some of the data displayed. We will also need at least one fake vendor's information in the database to help the front end visualize their design better.

## Details
* **Related Issues:** #38, #39, #41, #43 
* **Classes/Files Affected:** portfolio.html, database
* **Role:** Back end

**Comment by KLSharkey** [comment]
The vendor list is in the database and I believe Sean made the fake vendors. Can we close this issue?
