### ISSUE TITLE
create dynamic page to display vendor list

### ISSUE THREAD

**Issue by CatherineEvelyn** [CatherineEvelyn/wedding-planner#41]
## Problem
create a dynamic page with 7-tabs (one for each vendor's category) which will display the list of vendors for selected category. This issue focus on the 7-tabs functionality, not the layout/design. Each tab will selectively display all vendors from a single category (sort from database).

## Proposed solution
Data should be loaded dynamically using AJAX in a single page design. 
Clicking on a services section would load the data for that section into the view and replace the old view.

- [x] Make the route to vendor-list.html
- [x] Make vendor-list.html page
  - [x] Make the menu for selecting each service type
  - [x] Create vendor_list.html template that will load from database
  - [x] Integrate ajax to load vendor_list.html template
  - [x] Update history state on ajax calls for forward/backward navigation

## Possible Problems
This will require more attention to the history state since it won't be logged when the ajax call is made.

## Details
* **Related Issues:** #40 #42 #43 #45 #14 
* **Classes/Files Affected:** vendor-list.html
* **Role:** Back end, front end.

**Comment by Zafuzi** [comment]
Closed by pr #46
