### ISSUE TITLE
create booking button on vendor-list.html

### ISSUE THREAD

**Issue by CatherineEvelyn** [CatherineEvelyn/wedding-planner#43]
## Problem
On the list of vendors, each vendor need a button or something, for booking purpose (for example on Zach's screenshot he posted on slack, there is a plus symbol in the corner of each vendor's card, that can be used to book the vendor). The button/symbol/link has to function properly when clicked. This issue focus on functionality, we can start with something simple like this: (View Details will be "Book this vendor" or something like that) then let front end fix the visual.

![sample2](https://user-images.githubusercontent.com/28941875/31542453-e1148fb6-afc6-11e7-9ff3-5aff0e1c14de.jpg)

This codes will be used on multiple page (vendor-list.html and portfolio.html)

## Details
* **Related Issues:** #42 #41 #40 #39 #38 
* **Classes/Files Affected:** vendor-list.html, portfolio.html, user-account.html
* **Role:** Back end.

## Additional explanation
From user's perspective, when booking button is clicked, user will be directed to user-account.html and see the vendor information shows up on his/her digital organizer book. At this stage, you can have that info displayed just as plain text/string on a blank user-account.html page (front end will take over after user-account.html can properly display data from the database correctly).

**Comment by KLSharkey** [comment]
I added Zach onto this as well since it was his vendor dashboard this is based off of. The database as it is now allows for both and date and time (start and end time) booking for each vendor so we need to decide how we want to work with that.

**Comment by CatherineEvelyn** [comment]
Ignore the word "Vendor Dashboard" on the sample picture, I was just randomly grabbing an image of a list with something to click at the end of the column.

The link/button will be displayed on vendor-list.html and the connection to database will be closely related to issue #45 for Sean, Zach's issue is more about creating the 7 tabs which is just sorting vendors by their category when selecting what to display. Essentially, everyone's task is connected to this, but I was trying to divide the task to create the **entire** vendor-list.html page into several smaller, more specific tasks, so each individual know exactly which part of the page they will be working on.
