### ISSUE TITLE
fix registration form on signup.html

### ISSUE THREAD

**Issue by CatherineEvelyn** [CatherineEvelyn/wedding-planner#44]
## Problem
Registration form on sign up page need to have more than just username and password. When user sign up, they need to register their username, password, name, state, date of the wedding (optional), number of guest (optional), budget $$ (optional), etc.
When vendor sign up, they need to register their username, password, company name, contact person name, phone number, address, state, zip code, min price, max price, vendor's category, etc.

We need all of these information during registration so we can display it on vendor-account.html where the vendor can edit/manage it.

## Proposed solution
it maybe better if the design is not a replica of login.html so it's not confusing. Most of the time registration form always on a page without much visual design, sort of just a blank/clean white page, like when we register for email or facebook or anything. User need to focus filing out the forms so any visual design will seems like a distraction.

## Details
* **Related Issues:** #40 
* **Classes/Files Affected:** signup.html
* **Role:** Back end, front end.

**Comment by seanmstevens** [comment]
I'm mostly done with the front end portion for this one.
