### ISSUE TITLE
add ability to sort vendor's list on vendor-list.html

### ISSUE THREAD

**Issue by CatherineEvelyn** [CatherineEvelyn/wedding-planner#49]
## Problem
user should be able to sort or filter the vendor's list by location (state and/or zipcode), rating(optional, we could skip rating feature if there isn't enough time), min price, or max price.
This is a feature, so I didn't put high priority on this issue.

## Details
* **Related Issues:** #40 #41 #42 
* **Role:** Back end

**Comment by Zafuzi** [comment]
Closed as it's a duplicate of issue #58
